Royal-Navy/design-system-docs

components/presenters/Masthead/Masthead.stories.tsx
components/presenters/Masthead/Masthead.test.tsx
components/presenters/Masthead/Masthead.tsx
components/presenters/Sidebar/Sidebar.stories.tsx
components/presenters/Sidebar/Sidebar.test.tsx
components/presenters/Sidebar/Sidebar.tsx
components/presenters/Sidebar/SidebarMenu.tsx
components/presenters/Sidebar/SidebarMenuItem.tsx
components/presenters/Sidebar/index.tsx
components/presenters/Sidebar/partials/StyledButton.tsx
components/presenters/Sidebar/partials/StyledFrame.tsx
components/presenters/Sidebar/partials/StyledHeader.tsx
components/presenters/Sidebar/partials/StyledHomeLink.tsx
components/presenters/Sidebar/partials/StyledNavLink.tsx
components/presenters/Sidebar/partials/StyledNavList.tsx
components/presenters/Sidebar/partials/StyledNavSection.tsx
components/presenters/Sidebar/partials/StyledNavSectionTitle.tsx
components/presenters/Sidebar/partials/StyledSidebar.tsx
components/presenters/Sidebar/partials/StyledSidebarMenu.tsx
components/presenters/Sidebar/partials/StyledSidebarMenuItem.tsx
components/presenters/Sidebar/partials/StyledTitle.tsx

Closes #50
Add `Sidebar` presentational component.

feat(Components): Add Sidebar presenter

---

components/presenters/ContentPanel/ContentPanel.tsx
components/presenters/ContentPanel/LeftCol.tsx
components/presenters/ContentPanel/RightCol.tsx
components/presenters/ContentPanel/constants.ts
components/presenters/ContentPanel/index.ts
components/presenters/ContentPanel/partials/StyledContentPanel.tsx
components/presenters/ContentPanel/partials/StyledLeftCol.tsx
components/presenters/ContentPanel/partials/StyledRightCol.tsx
components/presenters/Hero/Hero.stories.tsx
components/presenters/Hero/Hero.test.tsx
components/presenters/Hero/Hero.tsx
components/presenters/Hero/index.ts
components/presenters/Hero/partials/StyledIllustration.tsx
components/presenters/Hero/partials/StyledLeftCol.tsx
components/presenters/Hero/partials/StyledPageDescription.tsx
components/presenters/Hero/partials/StyledPageTitle.tsx

Closes #49, #44
Add `Hero` and `ContentPanel` presenters.

feat(Components): Add Hero presenter

---

components/presenters/CodeBlock/CodeBlock.stories.tsx
components/presenters/CodeBlock/CodeBlock.test.tsx
components/presenters/CodeBlock/CodeBlock.tsx
components/presenters/CodeBlock/index.ts
components/presenters/CodeBlock/partials/StyledCodeBlock.tsx
components/presenters/CodeBlock/partials/StyledFilename.tsx
components/presenters/CodeBlock/partials/StyledHeader.tsx
components/presenters/CodeBlock/partials/StyledHighlight.tsx
jest.config.js
package.json
yarn.lock

Closes #46 
Add `CodeBlock` presenter.
I've taken the liberty of changing the syntax highlighting theme. We can always change it back later.

feat(Components): Add CodeBlock presenter

---

.github/workflows/build_and_test_feature.yml
.github/workflows/build_and_test_master.yml
package.json
sonar-project.properties
yarn.lock

closes #79 
Add project to Sonarcloud

ci(Sonarcloud): Add sonarcloud

---

.gitignore
components/adapters/ApiTableAdapter.tsx
components/adapters/ContentBlockAdapter.tsx
components/layouts/Framework/Framework.tsx
components/presenters/ApiTable/ApiTableItem.tsx
components/presenters/ApiTable/index.ts
components/presenters/ContentPanel/partials/StyledContentPanel.tsx
components/presenters/Section/Section.tsx
components/presenters/Section/index.ts
components/presenters/Section/partials/StyledSection.tsx
components/presenters/Sidebar/Sidebar.tsx
components/presenters/Sidebar/SidebarMenu.tsx
graphql/index.ts
pages/index.tsx

Closes #83 
Render `defaultValue` field JSON.

feat(ApiTableAdapter): Render `defaultValue` JSON

---

components/adapters/ApiTableAdapter.tsx
components/presenters/ApiTable/ApiTableItem.tsx

Missing tag was causing off formatting.

fix(ApiTableAdapter): Add missing `p` tag for description

---

components/layouts/Framework/Framework.test.tsx
components/layouts/Framework/Framework.tsx
components/presenters/Sidebar/Sidebar.tsx
jest/setupTests.js
package.json
yarn.lock

A few quick tweaks ahead of go-live.

feat(TimelineMicrosite): Pre-deployment tweaks

---

.github/workflows/manual_release.yml

closes #107 
Add manual release workflow

ci(Release): Add manual release workflow

---

.github/workflows/manual_release.yml
.github/workflows/release.yml

closes #116 
Fix for release workflows

ci(Release): Update tokens in release workflows

---

pages/_app.tsx
tsconfig.json
yarn.lock

Nuke lockfile and apply sensible TS default required by prod build.

fix(Build): Nuke lockfile and apply sensible TS default

---

.github/workflows/build_and_test_feature.yml

closes #132 
Set build & test feature workflow to run against the contentful staging environment

ci(GHA): Add staging environment variable

---

babel.config.js
components/helpers.ts
components/presenters/OnThisPage/OnThisPage.stories.tsx
components/presenters/OnThisPage/OnThisPage.test.tsx
components/presenters/OnThisPage/OnThisPage.tsx
components/presenters/OnThisPage/OnThisPageItem.tsx
components/presenters/OnThisPage/index.ts
components/presenters/OnThisPage/partials/StyledHeading.tsx
components/presenters/OnThisPage/partials/StyledItem.tsx
components/presenters/OnThisPage/partials/StyledItems.tsx
components/presenters/OnThisPage/partials/StyledOnThisPage.tsx

Closes #149 
Adds the `OnThisPage` presentational component.
One of the lego bricks for the Docs Site.

feat(OnThisPage): Add component

---

.github/workflows/project_issues.yml

closes #160 
Fix move issues workflow
Not working for medium labelled issues

ci(GHA): Remove space in label-name value

---

components/presenters/Docs/Footer/Footer.tsx
components/presenters/Docs/Footer/partials/StyledCopyright.tsx
components/presenters/Docs/Footer/partials/StyledDescription.tsx
components/presenters/Docs/Footer/partials/StyledFooter.tsx
components/presenters/Docs/Footer/partials/StyledFooterLogo.tsx
components/presenters/Docs/Footer/partials/StyledLinkList.tsx
components/presenters/Docs/Footer/partials/StyledNelsonLogoClip.tsx
components/presenters/Docs/Footer/partials/StyledSubFooter.tsx

Closes #169
Implements mobile version of `Footer`.
Adding all components for new layout.

feat(Footer): Implement mobile CSS

---

.github/workflows/build_and_test_feature.yml

ci(GHA): Add condition to set Contentful env

---

.github/dependabot.yml

ci(Security): Enable dependabot

---

.github/workflows/branch_deploy.yml

closes #189
Add branch deployment workflow to allow docs site previews for feature branches

ci(GHA): Add branch deploy workflow

---

yarn.lock

Update lock file to address security issues in flagged deps:
https://www.npmjs.com/advisories/1771
https://www.npmjs.com/advisories/1778

chore(Security): Update lock file

---

SECURITY.md

closes #228 
Add security policy
https://github.com/Royal-Navy/docs.royalnavy.io/blob/docs/security/SECURITY.md

docs(Security): Add security policy

---

LICENSE
README.md

docs(License): Add license

---

components/layouts/Legacy/partials/StyledContent.tsx
cypress/specs/docs/index.spec.ts
pages/[...slug].tsx

Closes #205
Add additional top margin to sub-headings to improve vertical rhythm.
>Sub-headings were too bunched up. Actioning feedback from designers.
Note earlier PRs that should first be reviewed and merged before this one.

staging_feat(StyledContent): Add additional top margin to sub-headings

---

components/layouts/Legacy/partials/StyledContent.tsx
components/layouts/Legacy/partials/StyledOnThisPageWrapper.tsx
components/presenters/Docs/Masthead/Masthead.test.tsx
components/presenters/Docs/Masthead/Masthead.tsx
components/presenters/Docs/Masthead/MastheadMenuItem.tsx
components/presenters/Docs/OnThisPage/partials/StyledOnThisPage.tsx
cypress/specs/docs/index.spec.ts
pages/[...slug].tsx

Closes #208
Make sticky on scroll and maintain visibility within viewport.
>You should be able to see this component no matter where your vertical scroll is within the page.

staging_feat(OnThisPage): Make sticky on scroll

---

components/layouts/Legacy/Legacy.stories.tsx
components/layouts/Legacy/partials/StyledContent.tsx
components/layouts/Legacy/partials/StyledOnThisPageWrapper.tsx
components/presenters/Docs/Masthead/Masthead.test.tsx
components/presenters/Docs/Masthead/Masthead.tsx
components/presenters/Docs/Masthead/MastheadMenuItem.tsx
components/presenters/Docs/OnThisPage/partials/StyledOnThisPage.tsx
components/presenters/Docs/Sidebar/Sidebar.stories.tsx
components/presenters/Docs/Sidebar/Sidebar.test.tsx
components/presenters/Docs/Sidebar/SidebarFilter.tsx
components/presenters/Docs/Sidebar/partials/StyledFilterIcon.tsx
components/presenters/Docs/Sidebar/partials/StyledFilterInputWrapper.tsx
cypress/specs/docs/index.spec.ts
graphql/index.ts
graphql/queries/PageByPath.graphql
package.json
pages/[...slug].tsx
yarn.lock

Closes #206
Group `Sidebar` items by Contentful tag and fix sticky state bug.
>Sidebar items should be grouped based on tags applied within the Contentful CMS.

staging_feat(Sidebar): Group sidebar items by tag

---

components/adapters/Docs/ContentBlockAdapter.tsx

Fixes the scroll position bug for the On This Page sidebar links

Staging feat/section header offset

---

components/layouts/Legacy/partials/StyledBody.tsx
components/layouts/Legacy/partials/StyledPageWrapper.tsx
components/presenters/Docs/Masthead/partials/StyledMasthead.tsx
components/presenters/Docs/PageBanner/PageBanner.tsx
components/presenters/Docs/PageBanner/partials/StyledPageBanner.tsx

Closes #287 
Prevent the PageBanner from leaving whitespace on close.

staging_fix(PageBanner): Change Masthead offset on close

---

components/presenters/Docs/Button/partials/StyledButton.tsx
components/presenters/Docs/Masthead/Masthead.test.tsx
components/presenters/Docs/Masthead/partials/StyledMastheadMenu.tsx

2 small commits to add animation to the masthead mobile menu and to add interaction states to the buttons.

Mobile menu animation & button animation

---

components/presenters/Docs/MarkdownTable/MarkdownTable.tsx

staging_fix(Styling): Resolve table nowrap on mobile

---

cypress/specs/docs/homepage.spec.ts

Update Cypress test now Contentful navigation has changed.

staging_fix(Cypress): Update e2e test

---

.github/workflows/automerge.yml
.github/workflows/build_and_test_feature.yml
.github/workflows/build_and_test_master.yml
.github/workflows/project_issues.yml
sonar-project.properties

Update workflows to reflect name change

ci(GHA): Update repo/action references in workflows

---

.github/workflows/project_issues.yml

ci(GHA): Update action in move issues workflow

---

.github/workflows/build_and_test_feature.yml
cypress/specs/docs/homepage.spec.ts

#383 
Change workflow trigger on build & test feature workflow to trigger on pull request (to bring in line with the DS workflow)

ci(GHA): Change workflow trigger

---

cypress/specs/docs/masthead.spec.ts
cypress/specs/timeline/index.spec.ts

Fixes #492
This updates the end-to-end tests following changes made to the docs site for the v3 release.
Make the tests pass again.

test(E2E): Update tests for v3 changes

---

pages/[...slug].tsx

Update hard coded URI in PageBanner that was leading to a 404.

fix(PageBanner): Update hardcoded upgrade guide URI

---

.github/workflows/release.yml

This reverts commit 757653355872e8d96b2d7cfca2d13383b3c2b148 and re-enables automated releases.

ci(GHA): Re-enable automated releases

---

.github/CODEOWNERS

n/a
Update codeowners
n/a
New maintainers

Chore(CODEOWNERS):Update maintainers

---

.github/workflows/manual_release.yml
.github/workflows/project_issues.yml
.github/workflows/release.yml

n/a
Update actions workflows
n/a
Rename back to RN

chore(GHA): Update workflows
