.gitignore
components/presenters/ApiTable/ApiTable.stories.tsx
components/presenters/ApiTable/ApiTable.test.tsx
components/presenters/ApiTable/ApiTable.tsx
components/presenters/ApiTable/ApiTableDefaultValue.tsx
components/presenters/ApiTable/ApiTableDescription.tsx
components/presenters/ApiTable/ApiTableFunctionParameter.tsx
components/presenters/ApiTable/ApiTableItem.tsx
components/presenters/ApiTable/index.ts
components/presenters/ApiTable/partials/StyledBody.tsx
components/presenters/ApiTable/partials/StyledBodyRow.tsx
components/presenters/ApiTable/partials/StyledBodyRowItem.tsx
components/presenters/ApiTable/partials/StyledBodyRowValue.tsx
components/presenters/ApiTable/partials/StyledHeader.tsx
components/presenters/ApiTable/partials/StyledHeaderRequired.tsx
components/presenters/ApiTable/partials/StyledHeaderTitle.tsx
components/presenters/ApiTable/partials/StyledItem.tsx
components/presenters/ApiTable/partials/StyledParameter.tsx
components/presenters/ApiTable/partials/StyledParameterName.tsx
components/presenters/ApiTable/partials/StyledParameterType.tsx
components/presenters/ApiTable/partials/StyledParameters.tsx
package.json
yarn.lock

Closes #45 
Adds `ApiTable`
Required for documenting Design System components.

Add API Table component

---

components/presenters/ApiTable/ApiTable.stories.tsx
components/presenters/ApiTable/ApiTableDefaultValue.tsx
components/presenters/LiveExample/LiveExample.stories.tsx
components/presenters/LiveExample/LiveExample.test.tsx
components/presenters/LiveExample/LiveExample.tsx
components/presenters/LiveExample/partials/StyledLiveExample.tsx

Closes #47 
Adds the `LiveExample` component.
Required for presenting live examples of code.
Leaving the headings for now. May rethinking this later.

Add LiveExample component

---

components/adapters/ApiTableAdapter.tsx
components/adapters/CodeBlockAdapter.tsx
components/adapters/ContentBlockAdapter.tsx
components/adapters/HeroAdapter.tsx
components/adapters/LiveExampleAdapter.tsx
graphql/index.ts
graphql/queries/SectionContent.graphql

Closes #74
Render embedded and reference media within rich text field type.
>Referenced and embedded images need to be rendered.
This will need to be expanded upon to support video.

feat(ContentBlockAdapter): Enable rich text media

---

components/adapters/ContentBlockAdapter.tsx
graphql/index.ts
graphql/queries/PageStructure.graphql
graphql/queries/SectionContent.graphql
services/contentful.ts

Rich Text Field embedded asset rendering has been disabled for now because it dramatically increases query complexity.
In the meantime, ensure that assets have their own fields.
https://www.contentful.com/developers/docs/references/graphql/#/introduction/query-complexity-limits

fix(Contentful): Further reduce query complexity

---

components/presenters/Sidebar/SidebarMenuItem.tsx
components/presenters/Sidebar/partials/StyledNavLink.tsx
pages/index.tsx

APITable content sections should be styled differently in the sidebar.

fix(Sidebar): Style APITable content sections differently

---

README.md
components/presenters/ApiTable/ApiTable.tsx
components/presenters/CodeBlock/CodeBlock.tsx
components/presenters/LiveExample/LiveExample.tsx
components/presenters/Sidebar/Sidebar.tsx
cypress.json
cypress/plugins/index.ts
cypress/selectors/hero.ts
cypress/selectors/index.ts
cypress/selectors/masthead.ts
cypress/selectors/sidebar.ts
cypress/specs/timeline/index.spec.ts
cypress/support/commands.ts
cypress/support/index.ts
jest.config.js
package.json
tsconfig.json
yarn.lock

Closes #91 
Adds e2e tests using Cypress.
Prevent regressions and better document features.
https://user-images.githubusercontent.com/56078793/115535746-f5eef280-a290-11eb-8a35-b32334dad3d9.mp4
Run `yarn test:e2e --headed` 🚀

Add e2e tests using Cypress

---

.github/workflows/manual_release.yml
.github/workflows/release.yml

closes #118 
Drop 'v' prefix for release version in release workflows

ci(Release): Drop v prefix for release version

---

components/adapters/ApiTableAdapter.tsx
components/presenters/ContentPanel/partials/StyledContentPanel.tsx
cypress/selectors/apiTable.ts
cypress/selectors/codeBlock.ts
cypress/selectors/index.ts
cypress/selectors/liveExample.ts
cypress/specs/timeline/index.spec.ts
graphql/index.ts
graphql/queries/SectionContent.graphql
services/contentful.ts

Closes #125 
Adds documentation for `useTimelineFrame` and `useTimelineZoom`
Hooks were recently exposed.
- Add `NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=staging` to `.env.local`

Add documentation for `useTimelineFrame` and `useTimelineZoom`

---

components/presenters/ApiTable/ApiTable.tsx
cypress/specs/timeline/index.spec.ts

Drill props to `ApiTable`, required for drilling `api-return-table`.

test(ApiTable): Fix drilling of `data-testid`

---

sonar-project.properties

Exclude Storybook stories from SonarCloud coverage reports.

ci(SonarCloud): Exclude stories from coverage

---

components/presenters/Docs/ContentBanner/ContentBanner.stories.tsx
components/presenters/Docs/ContentBanner/ContentBanner.test.tsx
components/presenters/Docs/ContentBanner/ContentBanner.tsx
components/presenters/Docs/ContentBanner/index.ts
components/presenters/Docs/ContentBanner/partials/StyledContentBanner.tsx
components/presenters/Docs/ContentBanner/partials/StyledDescription.tsx
components/presenters/Docs/ContentBanner/partials/StyledTitle.tsx

Closes #148
Create base `ContentBanner` presentational component.
>Create all presentational components in 'legacy' docs-site mocks.
https://github.com/Royal-Navy/docs.royalnavy.io/pull/165 should be merged ahead of this PR.

feat(ContentBanner): Create base component

---

components/layouts/Docs/Component.stories.tsx
components/layouts/Docs/Component.test.tsx
components/layouts/Docs/Component.tsx
components/layouts/Docs/index.ts
components/layouts/Docs/partials/StyledArticle.tsx
components/layouts/Docs/partials/StyledBody.tsx
components/layouts/Docs/partials/StyledContent.tsx
components/layouts/Docs/partials/StyledMain.tsx
components/layouts/Docs/partials/StyledMastheadWrapper.tsx
components/layouts/Docs/partials/StyledOnThisPageWrapper.tsx
components/layouts/Docs/partials/StyledPageWrapper.tsx
components/layouts/Docs/partials/StyledSidebarWrapper.tsx
components/layouts/Docs/partials/StyledTitle.tsx
components/presenters/Docs/Footer/Footer.tsx
components/presenters/Docs/Footer/partials/StyledFooter.tsx
components/presenters/Docs/Masthead/partials/StyledMasthead.tsx
components/presenters/Docs/OnThisPage/partials/StyledOnThisPage.tsx
components/presenters/Docs/Sidebar/Sidebar.tsx
components/presenters/Docs/Sidebar/SidebarMenu.tsx

Closes #155 
Adds the layout for the component pages.
Required for presenting component docs.
There is [an issue](https://github.com/Royal-Navy/docs.royalnavy.io/issues/179) with the footer SVG which gives horizontal scrolling in the mobile view.

Add component layout

---

jest.config.js
package.json
yarn.lock

Set global test environment to jsdom:
https://www.npmjs.com/package/jest-environment-jsdom-global
https://jestjs.io/docs/configuration#testenvironment-string

test(Jest): Set global test environment to jsdom

---

.github/workflows/automerge.yml
.github/workflows/build_and_test_feature.yml
.github/workflows/build_and_test_master.yml
cypress.json

Closes #111 
Capture screenshots for failed e2e tests, save as a workflow artifact
https://github.com/Royal-Navy/docs.royalnavy.io/actions/runs/1150255043
Assist debugging when e2e tests fail

ci(E2E_tests): Capture screenshots for failed end to end tests

---

cypress/specs/docs/index.spec.ts
pages/[...slug].tsx

Closes #207
Handle edge case where a navigation item has no associated page.
>Navigation and pages do not always have a like-for-like relationship.

staging_feat(Navigation): Handle nav item with no associated page

---

components/layouts/Legacy/partials/StyledContent.tsx
components/presenters/Docs/Masthead/Masthead.test.tsx
components/presenters/Docs/Masthead/Masthead.tsx
components/presenters/Docs/Masthead/MastheadMenuItem.tsx
cypress/specs/docs/index.spec.ts
pages/[...slug].tsx

Closes #203
Hide sub menu on document click.
>Sub menu should be hidden when a click event fired outside of the containing element.

staging_feat(Masthead): Close nav sub menu on page click

---

components/layouts/Legacy/Legacy.stories.tsx
components/layouts/Legacy/partials/StyledContent.tsx
components/layouts/Legacy/partials/StyledOnThisPageWrapper.tsx
components/presenters/Docs/Masthead/Masthead.test.tsx
components/presenters/Docs/Masthead/Masthead.tsx
components/presenters/Docs/Masthead/MastheadMenuItem.tsx
components/presenters/Docs/OnThisPage/partials/StyledOnThisPage.tsx
components/presenters/Docs/Sidebar/Sidebar.stories.tsx
components/presenters/Docs/Sidebar/Sidebar.test.tsx
components/presenters/Docs/Sidebar/SidebarFilter.tsx
components/presenters/Docs/Sidebar/partials/StyledFilterIcon.tsx
components/presenters/Docs/Sidebar/partials/StyledFilterInputWrapper.tsx
cypress/specs/docs/index.spec.ts
pages/[...slug].tsx

Closes #204
Change behaviour of sidebar filter input from clear button to keyboard ('/' key) activated focus.
>This behaviour was incorrectly implemented based on assumptions made from mocks.
No current spec for styling associated with behaviour - designer needs to do this.

staging_feat(Sidebar): Change filter clear to keyboard shortcut

---

components/adapters/Docs/ContentBlockAdapter.tsx
components/adapters/Docs/__tests__/ContentBlockAdapter.test.tsx
components/presenters/Docs/MarkdownTable/MarkdownTable.stories.tsx
components/presenters/Docs/MarkdownTable/MarkdownTable.test.tsx
components/presenters/Docs/MarkdownTable/MarkdownTable.tsx
components/presenters/Docs/MarkdownTable/index.ts
graphql/index.ts
graphql/queries/PageByPath.graphql
package.json
yarn.lock

Closes #246 
Renders a markdown table on the page.
> When entering table data using Markdown, the Markdown is not interpreted and just displays the characters verbatim.

Add ability to display tables

---

components/adapters/Docs/ContentBlockAdapter.tsx
components/adapters/Docs/__tests__/ContentBlockAdapter.test.tsx
graphql/index.ts
graphql/queries/PageByPath.graphql

Closes #245
Presents embedded code blocks on the page.
> Format Embedded In-line Code Blocks so that they display in the UI
Styles will be sorted by @hxltrhuxze

Present embedded code blocks

---

components/adapters/Docs/ContentBlockAdapter.tsx
components/adapters/Docs/__tests__/ContentBlockAdapter.test.tsx
components/presenters/Docs/Swatch/Swatch.stories.tsx
components/presenters/Docs/Swatch/Swatch.test.tsx
components/presenters/Docs/Swatch/Swatch.tsx
components/presenters/Docs/Swatch/SwatchColour.tsx
components/presenters/Docs/Swatch/index.ts
components/presenters/Docs/Swatch/partials/StyledColour.tsx
components/presenters/Docs/Swatch/partials/StyledLabel.tsx
components/presenters/Docs/Swatch/partials/StyledSwatch.tsx
graphql/index.ts
graphql/queries/PageByPath.graphql

Closes #247 
Adds the ability to display a colour swatch using a React component backed by the Contentful content model.
> The colour swatches in the Styles/Colours section can only be displayed as images at present. There is no way to publish HTML. This means that the desktop and mobile experience of the docs site will be impaired.

Add swatch

---

babel.config.js
components/presenters/Docs/Badge/Badge.tsx
components/presenters/Docs/Hero/Hero.tsx
components/presenters/Docs/Masthead/Masthead.test.tsx
components/presenters/Docs/Masthead/Masthead.tsx
components/presenters/Docs/Masthead/MastheadMenuItem.tsx
components/presenters/Docs/Masthead/partials/StyledLogo.tsx
cypress/selectors/docs/layout.ts
cypress/specs/docs/index.spec.ts
graphql/queries/NavigationByID.graphql
package.json
pages/[...slug].tsx
pages/index.tsx
yarn.lock

Closes #275
Closes #278
Closes #279
Closes #281
Closes #302
Closes #304
Closes #290
Closes #310
Disable auto-close of expanded sub-menu on document click (@ mobile).
Only render sub-menu where children exist.
Mobile UX was poor when expanding / collapsing navigation sub-menus.

staging_fix(Masthead): Resolve numerous small navigation quirks

---

components/adapters/Docs/ContentBlockAdapter.tsx
components/adapters/Docs/__tests__/ContentBlockAdapter.test.tsx
cypress/specs/docs/components.spec.ts
pages/[...slug].tsx

Closes #92 
Use dashes instead of camelCase for content section IDs.
> more URL friendly and consistent with legacy URL structure

feat(ContentBlock): Use kebab-case

---

components/presenters/Docs/MarkdownTable/MarkdownTable.tsx
components/presenters/Framework/CodeBlock/partials/StyledCodeBlock.tsx

This PR styles the markdown table.
The 2nd commit deletes extra code from the `StyledCodeBlock` styles, which were causing the code block to not span full width.

Styled table (and code block fix)

---

components/presenters/Docs/Masthead/partials/StyledMastheadMenu.tsx
cypress/specs/docs/components.spec.ts
cypress/specs/docs/homepage.spec.ts
graphql/index.ts
package.json
pages/[...slug].tsx
pages/index.tsx
yarn.lock

Closes #314
Mobile should render a slightly different navigational structure.
>There isn't a way of accessing nested Reference pages at mobile because the Sidebar is hidden.

staging_fix(Masthead): Render different nav for mobile

---

components/adapters/Docs/ContentBlockAdapter.tsx
components/adapters/Docs/__tests__/ContentBlockAdapter.test.tsx
graphql/index.ts
graphql/queries/PageByPath.graphql

Fixes #289 
Changes `CodeBlock` content to be blocks rather than inline.
There will be a requirement to display other assets as inline but block is the most appropriate for `CodeBlock`.
- to test use `/tokens/breakpoints`, other content will be updated once approved

Fix `CodeBlock` to be block rather inline in Contentful

---

cypress/helpers.ts
cypress/specs/docs/components.spec.ts
graphql/index.ts
graphql/queries/PageByPath.graphql
pages/[...slug].tsx

Closes #300 
Change adds a `key` so that the `Component` updates and resets state when the path changes.
> "On this page" highlights the position of the previously selected heading. 
- https://github.com/vercel/next.js/issues/9992#issuecomment-615402511

Fix `OnThisPage` state not resetting when changing route

---

components/layouts/Legacy/Legacy.tsx
components/presenters/Docs/OnThisPage/OnThisPage.stories.tsx
components/presenters/Docs/OnThisPage/OnThisPage.test.tsx
components/presenters/Docs/OnThisPage/OnThisPage.tsx
components/presenters/Docs/OnThisPage/hooks/useActiveItem.ts
cypress/specs/docs/components.spec.ts
pages/[...slug].tsx

Fixes #331 
When browsing directly to a section or refreshing a page then the section is not highlighted.
> If you browse to /page#3-section then the corresponding OnThisPage item is not highlighted.

fix(OnThisPage): Fix browsing directly to a section

---

.github/workflows/manual_release.yml
.github/workflows/release.yml

closes #419 
Add slack notifications for failed releases.
As per design system

ci(GHA): Add failure notifications to release workflows

---

cypress/support/global.d.ts

This is currently breaking the build.
The following PR upstream will make this redundant once shipped: https://github.com/cypress-io/cypress/pull/19003

fix(Cypress): Add missing types post upgrade

---

next.config.js
public/googlec53f8692bc02cf64.html

The requested TXT record was unable to be added due to the site sitting on a CNAME.
I've since found an alternative way of enable the search console.
https://support.google.com/webmasters/answer/9008080#html_verification&zippy=%2Chtml-file-upload

chore(Google): Add URL prefix site verification

---

.github/workflows/automerge.yml
.github/workflows/build_and_test_feature.yml

Use existing action preset functionality to restrict automerge to minor and patch releases.
https://github.com/defencedigital/design-system-mergeme-action#presets

ci(Dependabot): Limit automerge to patch and minor

---

cypress/selectors/docs/homepage.ts
cypress/specs/docs/homepage.spec.ts
pages/index.tsx

fix(PageBanner): Update upgrade guide link

---

package.json
yarn.lock

This updates some dependencies to resolve various security alerts being flagged by `yarn audit`.
To resolve security alerts.

Resolve yarn audit security alerts

---

.github/CODEOWNERS
.github/dependabot.yml

This updates the CODEOWNERS file to remove those no longer on the project, and also removes reviewers from the Dependabot configuration as CODEOWNERS should be adding reviewers already.

chore(CODEOWNERS): Update CODEOWNERS and Dependabot reviewers

---

next.config.js
package.json
yarn.lock

It was causing a number of warnings when building:
```
warn  - Invalid next.config.js options detected: 
- The root value has an unexpected property, webpackDevMiddleware, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, …
```

build: Remove next-compose-plugins

---

.github/workflows/automerge.yml
.github/workflows/branch_deploy.yml
.github/workflows/build_and_test.yml
.github/workflows/manual_release.yml
.github/workflows/project_stale_issues.yml
.github/workflows/release.yml

This uploads all actions to their latest versions, to resolve warnings about actions using Node.js 12 no longer being supported.
There should be no relevant breaking changes in these updates.

ci(GHA): Update all actions to latest versions

---

.github/workflows/build_and_test.yml
cypress/e2e/docs/homepage.cy.ts
cypress/e2e/docs/masthead.cy.ts
cypress/e2e/docs/styles.cy.ts
cypress/e2e/timeline/index.cy.ts
package.json
yarn.lock

This updates Cypress from version 10 to version 12, and makes it use Chrome on GitHub Actions (instead of Electron).
Get Cypress on the latest version.
There was previously some flakiness when running the Timeline tests on GitHub Actions. I can also reproduce it locally if the CPU is stressed when running Cypress. I wasn't able to reproduce the flakiness with Chrome locally, hence this switches to that on CI as well.
By default, Cypress now isolates tests. This required updates to some tests so that they aren't dependent on previous tests.

Update Cypress to version 12 and use Chrome on GitHub Actions
